version: '3'

services:
  frontend:
    image: frontend-image
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html  # bind mount the frontend code to container
    # networks:
    #   - app-network
  
#   api:
#     image: api-image
#     build: ./api
#     ports:
#       - "8081:80"
#     environment:
#       - DATABASE_HOST=db
#     volumes:
#       - ./api:/var/www/html      # bind mount the API code to container
#     networks:
#       - app-network
#     depends_on:
#       - db
  
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_DATABASE: ecommerce  # This should match your database name
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#       MYSQL_ROOT_PASSWORD: password
#     volumes:
#       - db-data:/var/lib/mysql
#       - ./db/ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql  # Mount the SQL file
#     networks:
#       - app-network


#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: db
#       PMA_USER: user
#       PMA_PASSWORD: password
#     ports:
#       - "8082:80"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   db-data:
